language: cpp
sudo: required
os: linux
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake

compiler:
  - gcc

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version  
  - ./install_base.sh
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ./Frometon-Engine
