language: cpp
sudo: required
dist: xenial
before_install:
  - sudo apt-get install -y libgles2-mesa-dev
  - sudo apt-get install -y libglfw3-dev
  - sudo apt-get install -y libglew-dev
  - sudo apt-get install -y libglm-dev
  - sudo apt-get install -y libassimp-dev
  - sudo apt-get install -y freeglut3-dev
  - sudo apt-get install -y make
  - sudo apt-get install -y cmake

compiler:
  - gcc

script:
  - ./install_base.sh
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ./Frometon-Engine
