language: cpp

sudo: required

os: linux

dist: xenial

compiler:
  - gcc

before_install:
  - sudo apt-get install -y libgles2-mesa-dev
  - sudo apt-get install -y libglfw3-dev
  - sudo apt-get install -y libglew-dev
  - sudo apt-get install -y libglm-dev
  - sudo apt-get install -y libassimp-dev
  - sudo apt-get install -y freeglut3-dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake
      - make



script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version  
  - ./install_base.sh
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ./Frometon-Engine
